### ISSUE TITLE
播放音乐时服务端进程卡住，客户端不能执行任何操作

### ISSUE THREAD

**Issue by mocksonline** [ishland/VanillaMelody#1]
[Java Sound Sequencer/ERROR]: Uncaught exception in thread "Java Sound Sequencer"
java.lang.NullPointerException: Cannot invoke "javax.sound.midi.Sequence.getTickLength()" because "this.this$0.sequence" is null
        at com.sun.media.sound.RealTimeSequencer$PlayThread.run(RealTimeSequencer.java:1307) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

完整pastbin：
https://pastebin.com/Mzgb2Jhr

**Comment by ishland** [comment]
Please try reproduce again with latest version.
